sudo: required

services:
  - docker

language: python

python:
  - 3.6

cache: pip

install:
  - make docker.build
  - make local.up

script:
  - docker exec -t {{cookiecutter.project_slug}}.app make quality
  - docker exec -t {{cookiecutter.project_slug}}.app make static
  - docker exec -t {{cookiecutter.project_slug}}.app make test

after_success:
  - pip install -U codecov
  - docker exec -t {{cookiecutter.project_slug}}.app coverage xml
  - codecov

# TODO Follow the steps at https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry
# to define the DOCKER_USERNAME and DOCKER_PASSWORD environment variables. Uncomment once those are set.
#deploy:
#  provider: script
#  script: bash .travis/docker_push.sh
#  on:
#    branch: master
