version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: {{ cookiecutter.project_slug }}.app
    # TODO Update this with the appropriate prefix
    image: {{ cookiecutter.project_slug }}
    restart: always
    stdin_open: true
    tty: true
    volumes:
      # TODO Find a better solution for exposing these directories
      - logs:/logs/{{ cookiecutter.project_slug }}
      - media:/public/{{ cookiecutter.project_slug }}/media
  # TODO Add webserver (e.g. caddy or nginx)
volumes:
  logs:
  media:
