version: "3"
services:
  db:
    container_name: {{ cookiecutter.project_slug }}.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB={{ cookiecutter.project_slug }}
    image: postgres:11.1-alpine
  app:
    # NOTE: A command should be passed to the container via docker-compose run. This ensures we don't start
    # gunicorn unnecessarily, and run out of memory.
    entrypoint:
      - bash
      - -c
    environment:
      - SECRET_KEY=replace-me
      - DATABASE_URL=postgis://postgres:postgres@{{ cookiecutter.project_slug }}.db:5432/{{ cookiecutter.project_slug }}?connect_timeout=60
    links:
      - db
