version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: {{ cookiecutter.project_slug }}.app
    # TODO Update this with the appropriate prefix
    image: {{ cookiecutter.project_slug }}:latest
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - logs:/logs
      - media:/public/media/
      - static:/public/static/
  web:
    container_name: {{ cookiecutter.project_slug }}.web
    image: nginx:1.15-alpine
    links:
      - app
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - logs:/var/log/nginx
      - media:/public/media:ro
      - static:/public/static:ro
volumes:
  logs:
  media:
  static:
